Corrections warning
AgP42/sequencing pull request #3
Opened 2020-06-26 18:29 UTC by Naboleo

Sur les tests de différents type de triggers
Sur les valeurs par défaut

2020-06-26 18:49 UTC, AgP42 requested changes
Hello, 

merci de me faire tout le boulot ! ;-)

A part la coquille en ligne 263 ça me semble tout bon. 

Tu as testé avec toutes les conditions en application pour voir que ça marche toujours ? (et pas uniquement que ça vire les warnings quand on les utilise pas ?) 

Merci, A+
Agathe

2020-06-26 18:49 UTC, AgP42 commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
il manque un $ dans le foreach, non ?

2020-06-26 18:55 UTC, Naboleo commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
Hi !
Bien vu ! Oui il manque un $... A force on se croise les yeux
Les tests sont en cours, d'où le PR pour avoir les infos dans un coin. Je te fais un retour dès que possible
@+

2020-06-26 19:24 UTC, AgP42 commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
ok, alors je laisse le PR ouvert pour l'instant si t'as d'autres corrections à apporter et j'attends ton GO pour merger. 

merci beaucoup en tout cas ! ;-)

2020-06-26 19:36 UTC, Naboleo commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
Il n'y a pas de quoi. Il est sympa ce petit plugin

2020-06-28 15:45 UTC, AgP42 commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
Hello, tout est ok chez toi, je merge et passe en stable ?

2020-06-28 16:05 UTC, Naboleo commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
Salut
En fait c'est pas la bonne solution : en l'état c'est pas directement "countable". Et c'est pas non plus une chaine vide... 
Pour l'instant je sèche et j'ai pas trouvé de test correct...
Il faut que je creuse encore un peu mais pour l'instant je suis dans la pose de placo !
++

2020-06-28 17:14 UTC, AgP42 commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
;-)
Ya pas d'urgence de toute façon !
Et tu as essayé avec un "isset($trigger)" ?

Ben tu me dis quand tu as une bonne solution qui te conviens alors ! 

Moi je peux accoucher à tout instant (mais ça peut encore prendre au moins 3 semaines encore aussi...), donc si je te répond pas, c'est que j'ai d'autres priorités qui sont arrivées ! ;-)

A+

2020-06-28 18:59 UTC, Naboleo commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
Hé mais c'est une chouette nouvelle ça ! Félicitations (et bon courage)

Coté code, le isset() n'aide pas non plus, on a bien un retour à tous les coups ... 

Sauf trompage, ta classe utilse la fonction getConfiguration hérité de eqLogic =>
	public function getConfiguration($_key = '', $_default = '') {
		return utils::getJsonAttr($this->configuration, $_key, $_default);
	}

Qui elle exploite ce bout de code (bien degeu)
 	public static function getJsonAttr(&$_attr, $_key = '', $_default = '') {
		if (is_array($_attr)) {
			if ($_key == '') {
				return $_attr;
			}
		} else {
			if ($_key == '') {
				return is_json($_attr, array());
			}
			if ($_attr === '') {
				if (is_array($_key)) {
					foreach ($_key as $key) {
						$return[$key] = $_default;
					}
					return $return;
				}
				return $_default;
			}
			$_attr = json_decode($_attr, true);
		}
		if (is_array($_key)) {
			$return = array();
			foreach ($_key as $key) {
				$return[$key] = (isset($_attr[$key]) && $_attr[$key] !== '') ? $_attr[$key] : $_default;
			}
			return $return;
		}
		return (isset($_attr[$_key]) && $_attr[$_key] !== '') ? $_attr[$_key] : $_default;
	}

Je pensais que dans l’hypothèse où le trigger n'existait pas en base, on retournait $_default qui vaut '' d'après la primitive...
Mais ça n'a pas l'air d'aller....
Je pense que je vais coder une copie de cette fonction avec des traces et, en décomposant avec un exemple ça ira mieux. 

Avec un peu de chance j'aurai une soluce avant les 3 ans de ton futur bout de chou ^^

2020-06-29 19:10 UTC, AgP42 commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
Oui c'est une chouette nouvelle, mais bien fatiguant les dernières semaines ! 

Et si au lieu d'un count() tu testais que c'est un array ? 

Si on reprend l'erreur d'origine : 
`PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/plugins/sequencing/core/class/sequencing.class.php on line 258
`

Or l'argument attendu pour le foreach, c'est juste un array
Extrait de la doc php : 
```
foreach (array_expression as $value){
    //commandes
}
foreach (array_expression as $key => $value){
    //commandes
}
```

Donc s'assurer que la conf remonte un array et ne faire tourner le foreach que si oui, ça devrait résoudre le truc, non ?

++

2020-06-30 17:11 UTC, Naboleo commented on core/class/sequencing.class.php
> +        foreach (triggers_timerange as $triggerOrCond) {
Bien vu ! ça à l'air de bien marcher avec isArray()
Je réactive des séquences bidons pour bien passer dans les 3 cas et je met à jours le PR.
Il va falloir que je révise un truc quand même un array[] c'est normalement OK avec count()....

Courage de ton coté !
++

2020-07-03 15:50 UTC, Naboleo commented
Salut !
Tester depuis quelques jours sans soucis chez moi !
Donc quand tu auras le temps, tu pourras faire un nouvelle release... mais c'est pas le plus important du moment 
Courage !

2020-07-03 16:50 UTC, AgP42 approved these changes

2020-07-03 16:51 UTC, merged

2020-07-03 18:18 UTC, AgP42 commented
C'est mergé et la beta avec tes corrections est sur le market, je ferai aussi quelques tests et je la passe en stable aprés. 

Merci ;-)